apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-lpag
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-lpag
    app.kubernetes.io/part-of: cin4s-839-0033-app
  name: devfile-sample-lpag
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-lpag
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-lpag
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0033-tenant/cin4s-839-0033-app/devfile-sample-lpag@sha256:5aab5625b0b434cd82bc5e1d1102fb07c1c235537958634bf736483261fd552a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
